// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Gpu struct {
	ID                  int64           `json:"id"`
	Vendor              string          `json:"vendor"`
	Name                string          `json:"name"`
	CanonicalName       sql.NullString  `json:"canonical_name"`
	VramGb              sql.NullFloat64 `json:"vram_gb"`
	MemoryType          sql.NullString  `json:"memory_type"`
	MemoryBus           sql.NullInt64   `json:"memory_bus"`
	Pcie                sql.NullString  `json:"pcie"`
	ShadingUnits        sql.NullInt64   `json:"shading_units"`
	Tmus                sql.NullInt64   `json:"tmus"`
	Rops                sql.NullInt64   `json:"rops"`
	ReleaseDate         sql.NullString  `json:"release_date"`
	Architecture        sql.NullString  `json:"architecture"`
	MemoryBandwidthGbps sql.NullFloat64 `json:"memory_bandwidth_gbps"`
	Fp16Tflops          sql.NullFloat64 `json:"fp16_tflops"`
	Int8Tops            sql.NullFloat64 `json:"int8_tops"`
	TdpWatts            sql.NullInt64   `json:"tdp_watts"`
}

type GpuPciID struct {
	ID                int64          `json:"id"`
	VendorID          string         `json:"vendor_id"`
	DeviceID          string         `json:"device_id"`
	SubsystemVendorID sql.NullString `json:"subsystem_vendor_id"`
	SubsystemDeviceID sql.NullString `json:"subsystem_device_id"`
	GpuID             int64          `json:"gpu_id"`
	Source            string         `json:"source"`
	Confidence        float64        `json:"confidence"`
}

type User struct {
	ID        int64         `json:"id"`
	Username  string        `json:"username"`
	GpuID     sql.NullInt64 `json:"gpu_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}
