// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getGPUByName = `-- name: GetGPUByName :one
SELECT id, vendor, name, canonical_name, vram_gb, memory_type, memory_bus, pcie, shading_units, tmus, rops, release_date, architecture, memory_bandwidth_gbps, fp16_tflops, int8_tops, tdp_watts FROM gpus WHERE name = ?
`

func (q *Queries) GetGPUByName(ctx context.Context, name string) (Gpu, error) {
	row := q.db.QueryRowContext(ctx, getGPUByName, name)
	var i Gpu
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.Name,
		&i.CanonicalName,
		&i.VramGb,
		&i.MemoryType,
		&i.MemoryBus,
		&i.Pcie,
		&i.ShadingUnits,
		&i.Tmus,
		&i.Rops,
		&i.ReleaseDate,
		&i.Architecture,
		&i.MemoryBandwidthGbps,
		&i.Fp16Tflops,
		&i.Int8Tops,
		&i.TdpWatts,
	)
	return i, err
}
